require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Style/AsciiComments:
  Enabled: false

Layout/EndOfLine:
  Enabled: False

Style/Documentation:
  Enabled: false
