# .rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/migrate/*_devise_*.rb'

Style/AsciiComments:
  Enabled: false

Layout/EndOfLine:
  Enabled: False

Style/Documentation:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false
  Include:
    - db/migrate/*.rb

Rails/FilePath:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - "spec/**/*"
